image: node:18.14.1

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qy
  - apt-get install -y lftp
  - npm install -g pnpm # Instalar pnpm globalmente
  - node --version
  - pnpm --version # Verificar la versión de pnpm

build:
  stage: build
  script:
    - pnpm install # Usar pnpm para instalar las dependencias
    - pnpm run build # Ejecutar el build con pnpm
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - lftp -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST -e "
      set ssl:verify-certificate no;
      rm -rf /public_html/*;
      mirror -R -P 5 ./dist/ /public_html/;
      quit"
  only:
    - main
