FROM node:lts AS build

# Instalar pnpm
RUN npm install -g pnpm

# Establece el directorio de trabajo en /usr/src/app
WORKDIR /usr/src/app

COPY . .


RUN pnpm i
RUN npx astro preferences disable --global devToolbar
RUN pnpm run build

FROM httpd:2.4 AS runtime
COPY --from=build /usr/src/app/dist /usr/local/apache2/htdocs/
EXPOSE 80